# Generated by Django X.Y on YYYY-MM-DD HH:MM
from django.db import migrations, models

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # If there are any dependencies on other migrations, list them here
    ]

    operations = [
        migrations.CreateModel(
            name='Post',  # Class names should be capitalized by convention
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), 
                ('title', models.CharField(max_length=255)),  # Title field
                ('content', models.TextField()),  # Content field for the post
                ('img_url', models.URLField(blank=True, null=True)),  # URL field for image, allows empty values
                ('created_at', models.DateTimeField(auto_now_add=True)),  # Automatically set on creation
                ('updated_at', models.DateTimeField(auto_now=True)),  # Automatically updated on each save
            ],
        ),
    ]
